export const mmseQuestions = [
  {
    key: "dia_semana",
    label: "¿Qué día de la semana es hoy?",
    type: "select",
    options: [
      "Domingo",
      "Lunes",
      "Martes",
      "Miércoles",
      "Jueves",
      "Viernes",
      "Sábado",
    ],
  },
  {
    key: "dia_mes",
    label: "¿Qué día del mes es hoy?",
    type: "select",
    options: Array.from({ length: 31 }, (_, i) => (i + 1).toString()),
  },
  {
    key: "mes",
    label: "¿Qué mes es?",
    type: "select",
    options: [
      "Enero",
      "Febrero",
      "Marzo",
      "Abril",
      "Mayo",
      "Junio",
      "Julio",
      "Agosto",
      "Septiembre",
      "Octubre",
      "Noviembre",
      "Diciembre",
    ],
  },
  {
    key: "anio",
    label: "¿Qué año es?",
    type: "select",
    options: [new Date().getFullYear().toString()],
  },
  {
    key: "estacion",
    label: "¿En qué estación del año estamos?",
    type: "select",
    options: ["Primavera", "Verano", "Otoño", "Invierno"],
  },
  {
    key: "pais",
    label: "¿En qué país estamos?",
    type: "select",
    options: [
      "Colombia",
      "México",
      "España",
      "Argentina",
      "Perú",
      "Chile",
      "Venezuela",
      "Ecuador",
      "Uruguay",
      "Paraguay",
      "Bolivia",
      "Cuba",
      "Guatemala",
      "Honduras",
      "El Salvador",
      "Costa Rica",
      "Panamá",
      "Puerto Rico",
      "República Dominicana",
      "Estados Unidos",
      "Brasil",
      "Francia",
      "Alemania",
      "Italia",
      "Canadá",
      "Japón",
    ],
  },
  {
    key: "departamento",
    label: "¿En qué departamento o estado estamos?",
    type: "input",
    help: "Escriba el nombre del departamento o estado",
  },
  {
    key: "ciudad",
    label: "¿En qué ciudad estamos?",
    type: "input",
    help: "Escriba el nombre de la ciudad",
  },
  {
    key: "lugar",
    label: "¿En qué lugar (hospital, clínica, etc.) estamos?",
    type: "input",
    help: "Escriba el nombre del lugar",
  },
  {
    key: "piso",
    label: "¿En qué piso o planta estamos?",
    type: "input",
    help: "Escriba el número del piso o planta",
  },
  {
    key: "registro_palabras",
    label: "Repita estas tres palabras: manzana, mesa, moneda",
    type: "input",
    help: "Escriba las tres palabras separadas por comas",
  },
  {
    key: "atencion_calculo",
    label: "Reste 7 sucesivamente desde 100 (hasta cinco restas)",
    type: "input",
    help: "Escriba los resultados separados por comas (ejemplo: 93, 86, 79, 72, 65)",
  },
  {
    key: "memoria_reciente",
    label: "¿Cuáles eran las tres palabras mencionadas anteriormente?",
    type: "input",
    help: "Escriba las tres palabras separadas por comas",
  },
  {
    key: "nombrar_objetos",
    label: "Nombre estos dos objetos (reloj y lápiz)",
    type: "input",
    help: "Escriba los nombres de los objetos separados por comas",
  },
  {
    key: "repetir_frase",
    label: "Repita la frase: 'En un trigal había cinco perros'",
    type: "input",
    help: "Escriba la frase exactamente como se le dijo",
  },
  {
    key: "orden_tres_pasos",
    label:
      "Siga esta orden de tres pasos: tome este papel con la mano derecha, dóblelo por la mitad y colóquelo en el suelo",
    type: "select",
    options: ["Completado", "Parcialmente completado", "No completado"],
    help: "Seleccione si el paciente completó la orden",
  },
  {
    key: "leer_frase",
    label: "Lea y obedezca la frase escrita: 'Cierre los ojos'",
    type: "select",
    options: ["Completado", "No completado"],
    help: "Seleccione si el paciente cerró los ojos",
  },
  {
    key: "escribir_frase",
    label: "Escriba una frase completa y coherente",
    type: "input",
    help: "Escriba la frase que escribió el paciente",
  },
  {
    key: "copiar_dibujo",
    label: "Copie este dibujo (dos pentágonos superpuestos)",
    type: "select",
    options: ["Correcto", "Parcialmente correcto", "Incorrecto"],
    help: "Seleccione la calidad del dibujo copiado",
  },
];
